openapi: 3.1.0
info:
  version: 1.0.0
  title: AquaBalance App
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  description: This is a documentation of students app
tags:
  - name: Users
    description: Users operations
  - name: Water
    description: Operations about users
servers:
  - url: https://aquabalance-backend.onrender.com
  - url: http://127.0.0.1:5173
paths:
  # /v1/users/amount:
  #   get:
  #     $ref: ../swagger/paths/users/amount.yaml
  /v1/users/register:
    post:
      $ref: ../swagger/paths/users/register.yaml
  /v1/users/login:
    post:
      $ref: ../swagger/paths/users/login.yaml
  /v1/users/logout:
    post:
      $ref: ../swagger/paths/users/logout.yaml
  # /v1/users/user-info:
  #   get:
  #     $ref: ../swagger/paths/users/user-info.yaml
  /v1/users/update:
    patch:
      $ref: ../swagger/paths/users/update.yaml
  # /v1/users/refresh:
  #   post:
  #     $ref: ../swagger/paths/users/refresh.yaml
  # /request-reset-password:

  # /reset-pwd:

  # /get-oauth-url:

  # /confirm-oauth:

  # /v1/water:
  #   post:
  #     $ref: ../swagger/paths/water/post.yaml
  # /v1/water/daily:
  # /v1/water/monthly:

  # /water/{water_id}:
  #   get:
  #     $ref: ../swagger/paths/water/{water_id}/get.yaml
  #   patch:
  #     $ref: ../swagger/paths/water/{water_id}/patch.yaml
  #   delete:
  #     $ref: ../swagger/paths/water/{water_id}/delete.yaml
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
